name: Meson CI

on:
    workflow_dispatch:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    # Customize the Meson build type here ("plain", "debug", "debugoptimized", "release", "minsize", "custom".)
    BUILD_TYPE: debug
    CXX: g++-12
    CC: gcc-12

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install ninja-build build-essential libx11-dev gcc-12 g++-12 libwxgtk3.0-gtk3-dev libgtk-3-dev libsdl2-2.0-0 libsdl2-dev

            - name: Setup Meson
              run: |
                  python -m pip install --upgrade pip
                  pip install meson

            - name: Configure
              run: meson setup build -Dbuildtype=${{env.BUILD_TYPE}}

            - name: Build
              run: meson compile -C build

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: linux oopetris
                  path: ${{github.workspace}}/build/oopetris
